### ISSUE TITLE
'todo' is not defined

### ISSUE THREAD

**Issue by juceyjing** [nodejh/vue2-tutorials#1]
hi，i am a new man in vue,  the pro has error about like this "src/components/TodoList.vue says that the todo  is not defined" . 
todoAdd it is a component, so whether the need for value between components
```
 addTodo () {
        this.todos.push({
          text: todo,
          isCompleted: false
        })
      }
```

**Comment by nodejh** [comment]
Because `todo` is  indeed undefined in your code.

You could pass `todo` as a parameter to `addTodo()`  function.

```
 addTodo (todo) {
        this.todos.push({
          text: todo,
          isCompleted: false
        })
      }
```

**Comment by juceyjing** [comment]
好的，明白了，感谢回答。
