### ISSUE TITLE
可能是一个小错误

### ISSUE THREAD

**Issue by icaruseeee** [nodejh/vue2-tutorials#2]
![image](https://user-images.githubusercontent.com/16240302/38852276-c1d081c4-424b-11e8-8276-cbef245ca017.png)
这个地方直接这样写 好像会有todo未定义的错误
![image](https://user-images.githubusercontent.com/16240302/38852304-e36916ac-424b-11e8-9d89-de97db339aec.png)
这样写好像就行了

**Comment by nodejh** [comment]
确实是，多谢提醒
